version: 1

sources:
  - name: dbsales
    schema: public
    tables:
      - name: commodities
        description: "Table that contains historic data from commodities"
        columns:
          - name: Date
            description: "Date of observation"
          - name: Close
            description: "Closing price of commodity"
          - name: symbol
            description: "Commodity Ticker"
      
      - name: movimentacao_commodities
        description: "Tabela Seed"
        columns:
          - name: date
            description: "Date of transaction"
          - name: symbol
            description: "Symbol of commodity"
          - name: action
            description: Type of transaction (buy/sell)
          - name: quantity
            description: "Number of transactions"